/**
 * shoppingList/member/add - Add member to shopping list
 * POST /api/shoppingList/member/add
 * Authorized: Owner
 */

import { NextRequest, NextResponse } from "next/server";
import { extractUserIdentity, requireOwner } from "@/app/middleware/auth";
import { validateShoppingListMemberAddDtoIn } from "@/app/validation";
import {
  ShoppingListMemberAddDtoOut,
  UuAppResponse,
} from "@/app/dto";
import { mergeErrorMaps, ErrorCode, ErrorMessages, createErrorMap } from "@/app/utils/errors";

export async function POST(request: NextRequest) {
  // Parse request body
  let body;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      {
        dtoOut: {} as ShoppingListMemberAddDtoOut,
        uuAppErrorMap: createErrorMap("dtoIn", ErrorCode.INVALID_DTO_IN, ErrorMessages.INVALID_DTO_IN),
      },
      { status: 400 }
    );
  }

  // Validate dtoIn
  const validation = validateShoppingListMemberAddDtoIn(body);
  if (!validation.isValid) {
    return NextResponse.json(
      {
        dtoOut: {} as ShoppingListMemberAddDtoOut,
        uuAppErrorMap: validation.errors,
      } as UuAppResponse<ShoppingListMemberAddDtoOut>,
      { status: 400 }
    );
  }

  // Extract user identity
  const { identity, errors: authErrors } = extractUserIdentity(request);
  if (!identity) {
    return NextResponse.json(
      {
        dtoOut: {} as ShoppingListMemberAddDtoOut,
        uuAppErrorMap: authErrors,
      } as UuAppResponse<ShoppingListMemberAddDtoOut>,
      { status: 401 }
    );
  }

  // Authorization: Owner only
  // Mock check - in production would query database for shopping list owner
  const mockOwnerId = "mock-owner-id"; // Would be fetched from database
  const ownerCheck = requireOwner(identity, mockOwnerId);
  if (!ownerCheck.isOwner) {
    return NextResponse.json(
      {
        dtoOut: {} as ShoppingListMemberAddDtoOut,
        uuAppErrorMap: ownerCheck.errors,
      } as UuAppResponse<ShoppingListMemberAddDtoOut>,
      { status: 403 }
    );
  }

  // Return dtoOut with input data echoed back
  const dtoOut: ShoppingListMemberAddDtoOut = {
    awid: identity.awid,
    id: "...", // Would be generated by application logic
    userId: validation.dtoIn.userId,
    shoppingListId: validation.dtoIn.shoppingListId,
    role: validation.dtoIn.role || "Member",
  };

  return NextResponse.json({
    dtoOut,
    uuAppErrorMap: mergeErrorMaps(validation.errors, authErrors, ownerCheck.errors),
  } as UuAppResponse<ShoppingListMemberAddDtoOut>);
}

